### ISSUE TITLE
Look into adding mapillary images back

### ISSUE THREAD

**Issue by jedgar1mx** [CityOfDetroit/development-opportunities#6]
Old mapillary API no longer supported which causes for imagery to not load on application.

**Comment by jmcbroom** [comment]
Hey,

I have an implementation of how to fix this in base-unit-tools: https://github.com/CityOfDetroit/base-unit-tools/blob/main/src/components/MapillarySv.js

Here's how we solve this:
- Load the Mapillary vector tiles in map as a new source: https://github.com/CityOfDetroit/base-unit-tools/blob/c3114bc1ad6b10432d7e778fb127e22e37ff1afd/src/styles/mapstyle.js#L43-L48
- Create a mapbox Layer that exists, but is invisible - not with the visibility property but by setting opacity to 0: https://github.com/CityOfDetroit/base-unit-tools/blob/main/src/styles/mapstyle.js#L16676-L16698
- on Map `moveend`, query for all Mapillary images in the viewport & stash them in shared state, here, `svImages`: https://github.com/CityOfDetroit/base-unit-tools/blob/main/src/Explorer/ExplorerMap.js#L83-L91
- We then add some logic to the `MapillarySv` component to look at the `svImages` passed from the map, and a `feature` to find the nearest images/sequences to the feature, and pick one of those to display.

There's a bit more to it than that, but that's the general outline of the solution, to the use the map itself as a replacement API and then do the distance sorting ourselves client-side.

**Comment by jedgar1mx** [comment]
Nice!, I will look at your notes. Thank @jmcbroom
